name: checkov

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build_push_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Scan the Dockerfile (fail if vuln criteria is met)
        uses: addnab/docker-run-action@v3
        with:
            image: bridgecrew/checkov:latest
            options: -v ${{ github.workspace }}Dockerfile:Dockerfile
            run: |
                checkov -d . --framework dockerfile

      - name: Build an image from the Dockerfile
        run: |
          docker build -t docker.io/svagml/checkovdemo:1.0 .
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Push an image to Docker Hub
        run: |
          docker push docker.io/svagml/checkovdemo:1.0

#      - name: Install Trivy
#        run: |
#          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.44.1
#
#      - name: Run Trivy vulnerability scanner
#        uses: aquasecurity/trivy-action@master
#        with:
#          image-ref: 'docker.io/svagml/trivydemo:1.0'
#          #image-ref: 'index.docker.io/library/busybox'
#          #format: 'table'
#          exit-code: '1'
#          ignore-unfixed: true
#          vuln-type: 'os,library'
#          severity: 'CRITICAL,HIGH'
#          format: 'sarif'
#          output: 'trivy-results.sarif'

#      - name: Upload Trivy scan results to GitHub Security tab
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: 'trivy-results.sarif'
