# https://github.com/bridgecrewio/checkov-action/blob/master/README.md
name: checkov

on: [push]

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
  IMAGE_PATH: .
  REGISTRY_URL: docker.io
  #CONTAINER_REGISTRY_URI: docker.io/svagml/checkovdemo
  USER_NAME: svagml
  REPO_NAME: checkovdemo
  TAG_NAME: 1.2

jobs:
  checkov-image-scan:
    runs-on: ubuntu-latest
    name: checkov-image-scan
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        #uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          framework: dockerfile
          quiet: true # optional: display only failed checks
          soft_fail: true # optional: do not return an error code if there are failed checks
          log_level: WARNING # optional: set log level. Default WARNING
          dockerfile_path: .
          container_user: 1000 # optional: Define what UID and / or what GID to run the container under to prevent permission issues

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        
        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Security checks that do not pass will 'fail'.
        # An alternative is to add `continue-on-error: true` to the previous step
        # Or 'soft_fail: true' to checkov.
        if: success() || failure()
        with:
          sarif_file: results.sarif

      - name: Build the image after checkov scans the Dockerfile
        run: |
          docker build -t ${{ env.REGISTRY_URL }}/${{ env.USER_NAME }}/${{ env.REPO_NAME }}:${{ env.TAG_NAME }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Push an image to Docker Hub
        run: |
          docker push docker.io/svagml/checkovdemo:1.2
