name: Docker Image CI

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build_push_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/svagml/trivydemo:1.0 .
          
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.7.0

      - name: Setup Bats libs
        uses: brokenpip3/setup-bats-libs@0.1.0

      - name: Check out code
        uses: actions/checkout@v1

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.44.1

      - name: Test
        run: BATS_LIB_PATH=${{ env.BATS_LIB_PATH }} bats --recursive --timing .

        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Push an image to Docker Hub
        run: |
          docker push docker.io/svagml/trivydemo:1.0
