# https://github.com/bridgecrewio/checkov-action/blob/master/README.md

on: [push]

env:
  IMAGE_NAME: ${{ github.repository }}:${{ github.sha }}
  IMAGE_PATH: .

jobs:
  checkov-image-scan:
    runs-on: ubuntu-latest
    name: checkov-image-scan
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Build the image
        run: |
          docker build -t ${{ env.IMAGE_NAME }} ${{ env.IMAGE_PATH }}
          ls -lrta
          pwd
          #rm ~/.bridgecrew/credentials

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          quiet: true # optional: display only failed checks
          soft_fail: true # optional: do not return an error code if there are failed checks
          log_level: WARNING # optional: set log level. Default WARNING
          dockerfile_path: .
          container_user: 1000 # optional: Define what UID and / or what GID to run the container under to prevent permission issues
