name: checkov

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]
env:
  CONTAINER_VERSION: 1.1
    
jobs:
  build_push_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checking for checkov-results.sarif
        run: |
          echo "Working DIR:"
          echo
          pwd
          ls -lrt /home/runner/work/checkov-pipeline-demo/checkov-pipeline-demo
          echo
          #cat /work/results.sarif
          
      - name: Checkout repository # Required to mount the Github Workspace to a volume
        uses: actions/checkout@v2

      - name: Scan the Dockerfile (fail if vuln criteria is met)
        uses: addnab/docker-run-action@v3
        with:
            image: bridgecrew/checkov:latest
            options: |
              -v ${{ github.workspace }}/Dockerfile:/Dockerfile
              -v ${{ github.workspace }}/results_sarif.sarif:/results_sarif.sarif
              -w ${{ github.workspace }}
            run: |
              sh -c "checkov -d . --framework dockerfile --soft-fail -o sarif --output-file-path ."
              echo "Working DIR:"
              pwd
              echo
              echo "list files & dirs starting from root location:"
              ls -lrt /
              echo "list files & dirs starting from /output location:"
              ls -lrt /output
                
      - name: Upload checkov scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'results_sarif.sarif'

      - name: Build an image from the Dockerfile
        run: |
          docker build -t docker.io/svagml/checkovdemo:{{ env.CONTAINER_VERSION }} .
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Push an image to Docker Hub
        run: |
          docker push docker.io/svagml/checkovdemo:1.0


