name: checkov

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]
env:
  CONTAINER_VERSION: 1.1
    
jobs:
  build_push_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository # Required to mount the Github Workspace to a volume
        uses: actions/checkout@v3
        #uses: actions/checkout@v2

      - name: Scan the Dockerfile (fail if vuln criteria is met)
        uses: addnab/docker-run-action@v3
        with:
            image: bridgecrew/checkov:latest
            options: |
              -v ${{ github.workspace }}/Dockerfile:/Dockerfile
            run: |
              sh -c "checkov -d . --framework dockerfile --soft-fail -o sarif"
              echo "Working DIR:"
              pwd
              echo
              echo "test" > bob.sarif
              echo "list files & dirs starting from root location:"
              ls -lrt /
              echo "Cat files:"
              cat *.sarif

      - name: Checking for files
        run: |
          echo "Working DIR:"
          echo
          pwd
          ls -lrt /home/runner/work/checkov-pipeline-demo/checkov-pipeline-demo
          ls -lrt /
          echo
          #cat /work/results.sarif
                
      - name: Upload checkov scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        
        # Results are generated only on a success or failure
        # this is required since GitHub by default won't run the next step
        # when the previous one has failed. Security checks that do not pass will 'fail'.
        # An alternative is to add `continue-on-error: true` to the previous step
        # Or 'soft_fail: true' to checkov.
        if: success() || failure()
        with:
          sarif_file: 'results.sarif'

      - name: Build an image from the Dockerfile
        run: |
          docker build -t docker.io/svagml/checkovdemo:{{ env.CONTAINER_VERSION }} .
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Push an image to Docker Hub
        run: |
          docker push docker.io/svagml/checkovdemo:1.0


