name: checkov

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]
    
  workflow_dispatch:

jobs:
  build_push_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Scan the Dockerfile (fail if vuln criteria is met)
        uses: addnab/docker-run-action@v3
        with:
            image: bridgecrew/checkov:latest
            options: -v ${{ github.workspace }}/Dockerfile:/Dockerfile
            run: |
                checkov -d . --framework dockerfile --soft-fail -o cli -o sarif --output-file-path console,checkov-results.sarif

      - name: Build an image from the Dockerfile
        run: |
          docker build -t docker.io/svagml/checkovdemo:1.0 .
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Push an image to Docker Hub
        run: |
          docker push docker.io/svagml/checkovdemo:1.0

      - name: Upload checkov scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'checkov-results.sarif'
