name: Build, Scan and push Docker image upon release

on:
  # Build and push Docker images *only* for releases.
  release:
    types: [published] # , created, edited

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name
        if: github.event_name != 'pull_request'
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Get branch name on pull request
        if: github.event_name == 'pull_request'
        run: echo "BRANCH_NAME=$(echo ${GITHUB_HEAD_REF#refs/heads/})" >> $GITHUB_ENV
        
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/devopslifter/podinfo:${{ steps.get_version.outputs.VERSION }} .
          
      - name: Install Wiz CLI
        run: |
         curl -o wizcli https://wizcli.app.wiz.io/wizcli
         chmod +x wizcli
         
      - name: Authenticate to the Wiz API
        run: |
         WIZ_ENV=TEST ./wizcli auth --id ${{ secrets.WIZ_CLIENT_ID }} --secret ${{ secrets.WIZ_CLIENT_SECRET }}
         
      - name: Scan Docker Image
        run: |
         WIZ_ENV=TEST ./wizcli docker scan --image docker.io/devopslifter/podinfo:${{ steps.get_version.outputs.VERSION }}
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        
      - name: Push an image to Docker Hub
        run: |
          docker push docker.io/devopslifter/podinfo:${{ steps.get_version.outputs.VERSION }}

